### ISSUE TITLE
real_LidarBot repo is deleted

### ISSUE THREAD

**Issue by bahacan09** [TheNoobInventor/lidarbot#2]
Hi I am a 2nd grade student in Electrical Electronical Engineering. I follow to day a day your project. But today you delete your repo. Can you share with me for I having a ideas to solving my problems.

**Comment by TheNoobInventor** [comment]
Hello @bahacan09, I had no idea that you were following the project. I deleted it because I had some issues getting some parts to work with ROS2 Foxy, so I decided to  focus on ROS2 Humble. 

If you haven't checked these videos out, look at these from Articulated Robotics. He starts out with ROS2 Foxy and is using Raspberry Pi 4 and L298N Motor driver. Here is his YouTube channel:

https://www.youtube.com/@ArticulatedRobotics

He doesn't use an MPU6050, maybe when you get to that stage you can reach out to me. I hope this helps.

**Comment by bahacan09** [comment]
Thank you for your patience and reply. I'm following this channel. Good luck at your project.

**Comment by TheNoobInventor** [comment]
Thank you. I hope to get it done in the coming weeks. Good luck as well with your project.
